global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "frontend"
    static_configs:
      - targets: ["host.docker.internal:3000"]

  - job_name: "backend"
    static_configs:
      - targets: ["host.docker.internal:8080"]

  - job_name: "bot"
    static_configs:
      - targets: ["host.docker.internal:8000"]
