import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Registry } from './registry'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Mandaumzap',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <Registry>
        <body className={inter.className}>{children}</body>
      </Registry>
    </html>
  )
}
