import 'react-loading-skeleton/dist/skeleton.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Registry } from './registry'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'mandaumzap',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body
        className={inter.className}
        style={{
          fontFamily: 'Inter',
        }}
      >
        <Registry>{children}</Registry>
      </body>
    </html>
  )
}
