name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mandaumzap:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
              mkdir -p ~/app
              
              # Parar containers existentes
              docker-compose -f ~/app/docker-compose.prod.yml down || true
              
              # Remover imagem antiga
              docker rmi ${{ secrets.DOCKER_USERNAME }}/ecommerce:latest || true
              
              # Baixar nova imagem
              docker pull ${{ secrets.DOCKER_USERNAME }}/ecommerce:latest
              
              # Criar docker-compose.prod.yml
              cat > ~/app/docker-compose.prod.yml << 'EOL'
              ${{ secrets.COMPOSE }}
              EOL
              
              # Iniciar aplicação
              cd ~/app && docker-compose -f docker-compose.prod.yml up -d